# Generated by Django 5.0.2 on 2024-02-21 13:50

import petstragram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_slug'),
        ('photos', '0002_petphoto_created_at_petphoto_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='pets',
            field=models.ManyToManyField(blank=True, to='pets.pet'),
        ),
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(upload_to='pet_photos/', validators=[petstragram.photos.validators.validate_file_size]),
        ),
    ]
